server:
  port: 8088
spring:
  application:
    name: microservices-server
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-info-authentication-method: header
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: ${keycloak-client.id}
            provider: keycloak
            scope: openid
            redirect-uri: ${keycloak-client.redirect-uri}
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
keycloak-client:
  redirect-uri: http://127.0.0.1:8763/login/oauth2/code/keycloak
  id: microservicesClient
  realm: microservices
